function createfigure6(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 30-Sep-2018 17:38:43

% Create figure
figure1 = figure('PaperSize',[15 15]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Motor A','MarkerSize',2,'Marker','o',...
    'LineStyle','none');
set(plot1(2),'DisplayName','Motor B','MarkerSize',2,'Marker','o',...
    'LineStyle','none');
set(plot1(3),'DisplayName','Motor C','MarkerSize',2,'Marker','o',...
    'LineStyle','none');
set(plot1(4),'DisplayName','Motor A (model)');
set(plot1(5),'DisplayName','Motor B (model)');
set(plot1(6),'DisplayName','Motor C (model)');

% Create ylabel
ylabel('$n\;[rpm]$','FontName','Palatino Linotype','Interpreter','latex');

% Create xlabel
xlabel('$t\;[ms]$','FontName','Palatino Linotype','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 5000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 120]);
box(axes1,'on');
grid(axes1,'on');
axis(axes1,'square');
% Set the remaining axes properties
set(axes1,'FontSize',12,'GridAlpha',1,'GridLineStyle',':','MinorGridAlpha',...
    1);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','Interpreter','latex','FontSize',12);

