function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 29-Sep-2018 17:44:00

% Create figure
figure1 = figure('PaperSize',[15 15]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot

plot(X1,Y1(:),'DisplayName','$M\acute{e}r\acute{e}si\;eredm\acute{e}nyek$',...
    'MarkerSize',4,...
    'Marker','diamond',...
    'LineWidth',1.2)...
    %'Color',[0 0 0]


% Create ylabel
ylabel('$n\;[rpm]$','FontSize',16,'FontName','Palatino Linotype',...
    'Interpreter','latex');

% Create xlabel
xlabel('$t\;[s]$','FontSize',16,'FontName','Palatino Linotype',...
    'Interpreter','latex');

box(axes1,'on');
grid(axes1,'on');
axis(axes1,'square');
% Set the remaining axes properties
set(axes1,'GridAlpha',1,'MinorGridAlpha',1);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','Interpreter','latex');

