function createfigure(X1, YMatrix1)
%CREATEFIGURE1(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 07-Oct-2018 17:30:12

% Create figure
figure('InvertHardcopy','off','PaperSize',[15 15],'Color',[1 1 1]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Motor A','Marker','v');
set(plot1(2),'DisplayName','Motor B','Marker','diamond');
set(plot1(3),'DisplayName','Motor C','Marker','^');

% Create ylabel
ylabel('$U\;[V]$','FontSize',17.6,'Interpreter','latex');

% Create xlabel
xlabel('$PWM\;[-]$','FontSize',17.6,'Interpreter','latex');
yLim = [0 12];
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 12]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
grid(axes1,'on');
axis(axes1,'square');
% Set the remaining axes properties
set(axes1,'FontSize',16,'GridAlpha',1,'GridLineStyle',':','MinorGridAlpha',...
    1,'XMinorTick','on','XTick',[0 0.2 0.4 0.6 0.8 1],'XTickLabel',...
    {'0','0.2','0.4','0.6','0.8','1'},'YMinorTick','on','YTick',...
    [0 2 4 6 8 10 12],'YTickLabel',{'0','2','4','6','8','10','12'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','Interpreter','latex','FontSize',16);

