function [figure1] = createfigure3(dataX, dataY, axisNames, displayNames, xLim, yLim)
%CREATEFIGURE1(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 29-Sep-2018 18:02:01
close all
% Create figure
figure1 = figure('PaperSize',[15 15]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

Markers = ['v','^','diamond','square','o'];

% Create multiple lines using matrix input to plot
plot1 = plot(dataX,dataY,'LineWidth',2,'Parent',axes1);
for i=1:length(displayNames)
    %set(plot1(i),'DisplayName',displayNames(i),'Marker',Markers(i));
    set(plot1(i),'DisplayName',displayNames(i));
end

% Create xlabel
xlabel(axisNames(1),'FontName','Palatino Linotype','Interpreter','latex');
xlim([xLim(1) xLim(2)]);

% Create ylabel
ylabel(axisNames(2),'FontName','Palatino Linotype','Interpreter','latex');
ylim([yLim(1) yLim(2)]);

box(axes1,'on');
grid(axes1,'on');
axis(axes1,'square');
% Set the remaining axes properties
set(axes1,'FontSize',16,'GridLineStyle',':');
set(axes1,'GridAlpha',1,'MinorGridAlpha',1);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','Interpreter','latex','FontSize',16);

