function validation_figure_single(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 30-Nov-2018 23:05:27

% Create figure
figure1 = figure('PaperSize',[15 15]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Simulation','LineWidth',2);

% Create ylabel
ylabel('$i_a$ [A]','Interpreter','latex');

% Create xlabel
xlabel('t [s]','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 20]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-2 2]);
box(axes1,'on');
grid(axes1,'on');
axis(axes1,'square');
% Set the remaining axes properties
set(axes1,'FontSize',16,'TickLabelInterpreter','latex');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southwest');

